name: Build and test

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
 
env:
  dotnet-version: 9.0

jobs:
  AFL:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Install AFL
      run: ./scripts/install.sh
    - name: Disable core dumps
      run: sudo sh -c "echo core >/proc/sys/kernel/core_pattern"
    - name: Run AFL tests
      shell: pwsh
      run: ./scripts/test.ps1

  libFuzzer:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Run libFuzzer tests
      run: ./scripts/test-libfuzzer.ps1
