name: Build and test

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-preview.3.23178.7
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install AFL
      run: ./scripts/install.sh
    - name: Disable core dumps
      run: sudo sh -c "echo core >/proc/sys/kernel/core_pattern"
    - name: Run AFL tests
      shell: pwsh
      run: ./scripts/test.ps1
