name: Build and test

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  AFL:
    runs-on: ubuntu-latest

    env:
      dotnet-version: 9.0

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Install AFL
      run: ./scripts/install.sh
    - name: Disable core dumps
      run: sudo sh -c "echo core >/proc/sys/kernel/core_pattern"
    - name: Run AFL tests
      shell: pwsh
      run: ./scripts/test.ps1 ${{ env.dotnet-version }}

  libFuzzer:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: ["8.0", "9.0"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Run libFuzzer tests
      run: ./scripts/test-libfuzzer.ps1 ${{ matrix.dotnet-version }}
